---
- name: 'Load distribution specific settings for epel repository'
  include_vars: '{{ var_file }}'
  failed_when: false
  loop_control:
    loop_var: 'var_file'
  loop:
    - 'vars/{{ ansible_os_family | lower }}.yml'
    - 'vars/{{ ansible_distribution | lower }}.yml'
    - 'vars/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}.yml'
    - 'vars/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}.yml'
    #  |  debian.yml       |  redhat.yml
    #  |  ubuntu.yml       |  centos.yml
    #  |  ubuntu18.yml     |  centos8.yml
    #  v  ubuntu18.04.yml  |  centos8.4.yml

- block:
    - name: 'Install epel repository'
      package:
        name:  '{{ epel_pkg }}'
        state: 'present'
    - name: 'Update epel repository'
      package:
        name:  '{{ epel_pkg }}'
        state: 'latest'
  when: 'epel_install_epel | bool'


# epel requires PowerTools, HA (and more) repos to be activated:
#   https://fedoraproject.org/wiki/EPEL#Quickstart

- block:
    - name: 'Check if PowerTools repo is enabled'
      shell:
        cmd: 'dnf repolist --enabled | grep "^{{ epel_powertools_repo_name }}[ \t]*"'
        warn: false
      changed_when: false
      failed_when: false
      register: '_epel_powertools_repo_check'
    - name: 'Enable PowerTools'
      command:
        cmd: 'dnf config-manager --enable {{ epel_powertools_repo_name }}'
        warn: false
      when: '_epel_powertools_repo_check.rc != 0'
  when: 'epel_install_epel | bool'
...
